### ISSUE TITLE
No suitable version of LLVM was found...

### ISSUE THREAD

**Issue by ghost** [LinusDikomey/eyelang#1]
I get this error when compiling with cargo:

> error: No suitable version of LLVM was found system-wide or pointed
>               to by LLVM_SYS_140_PREFIX.
>        
>               Consider using `llvmenv` to compile an appropriate copy of LLVM, and
>               refer to the llvm-sys documentation for more information.
>        
>               llvm-sys: https://crates.io/crates/llvm-sys
>               llvmenv: https://crates.io/crates/llvmenv
>    --> /ev/.cargo/registry/src/github.com-1ecc6299db9ec823/llvm-sys-140.0.2/src/lib.rs:487:1
>     |
> 487 | / std::compile_error!(concat!(
> 488 | |     "No suitable version of LLVM was found system-wide or pointed
> 489 | |        to by LLVM_SYS_",
> 490 | |     env!("CARGO_PKG_VERSION_MAJOR"),
> ...   |
> 497 | |        llvmenv: https://crates.io/crates/llvmenv"
> 498 | | ));
>     | |__^
> 
> error: could not compile `llvm-sys` due to previous error

What version of LLVM is required anyway? I'm using 13.0.1. I specified LLVM_SYS_140_PREFIX but LLVM could not be found.

**Comment by LinusDikomey** [comment]
First up: thanks for trying out my language. It's still very early in development and I reworked some syntax just today. Many things are uncompleted/broken so don't expect a well-working language.
You will need LLVM version 14 for this to work. Set LLVM_SYS_140_PREFIX to the folder you built/installed it to. You can look at detailed instructions [here](https://crates.io/crates/llvm-sys).

**Comment by ghost** [comment]
I've updated llvm to version 14.0.6 and I got the same errors despite setting the LLVM_SYS_140_PREFIX. I removed the code that checked for llvm from the llvm-sys source code and it compiled but eyelang fails to compile because it uses unstable features:

> error[E0554]: `#![feature]` may not be used on the stable release channel
>   --> src/main.rs:1:1
>    |
> 1  | / #![feature(
> 2  | |     let_else,
> 3  | |     box_patterns,
> 4  | |     variant_count,
> ...  |
> 9  | |     generic_associated_types,
> 10 | | )]
>    | |__^
> 
> error[E0658]: use of unstable library feature 'path_try_exists'
>    --> src/main.rs:289:13
>     |
> 289 |         if !std::fs::try_exists("eyebuild").expect("Failed to check availability of eyebuild directory") {
>     |             ^^^^^^^^^^^^^^^^^^^
>     |
>     = note: see issue #83186 <https://github.com/rust-lang/rust/issues/83186> for more information
> 
> error[E0658]: use of unstable library feature 'path_try_exists'
>   --> src/compile.rs:54:27
>    |
> 54 |             Some(path) if std::fs::try_exists(&path).is_ok_and(|v| *v) => path,
>    |                           ^^^^^^^^^^^^^^^^^^^
>    |
>    = note: see issue #83186 <https://github.com/rust-lang/rust/issues/83186> for more information
> 
> error[E0658]: use of unstable library feature 'path_try_exists'
>   --> src/compile.rs:82:23
>    |
> 82 |     let base_exists = std::fs::try_exists(&base_file)
>    |                       ^^^^^^^^^^^^^^^^^^^
>    |
>    = note: see issue #83186 <https://github.com/rust-lang/rust/issues/83186> for more information
> 
> error[E0554]: `#![feature]` may not be used on the stable release channel
>  --> src/main.rs:4:5
>   |
> 4 |     variant_count,
>   |     ^^^^^^^^^^^^^
> 
> error[E0554]: `#![feature]` may not be used on the stable release channel
>  --> src/main.rs:5:5
>   |
> 5 |     fs_try_exists,
>   |     ^^^^^^^^^^^^^
> 
> error[E0554]: `#![feature]` may not be used on the stable release channel
>  --> src/main.rs:6:5
>   |
> 6 |     nonzero_ops,
>   |     ^^^^^^^^^^^
> 
> error[E0554]: `#![feature]` may not be used on the stable release channel
>  --> src/main.rs:7:5
>   |
> 7 |     is_some_with,
>   |     ^^^^^^^^^^^^
> 
> error[E0554]: `#![feature]` may not be used on the stable release channel
>  --> src/main.rs:8:5
>   |
> 8 |     int_log,
>   |     ^^^^^^^
> 
> error[E0635]: unknown feature `fs_try_exists`
>  --> src/main.rs:5:5
>   |
> 5 |     fs_try_exists,
>   |     ^^^^^^^^^^^^^
> 
I use rust version 1.61.0 which is not supporting those features.

**Comment by LinusDikomey** [comment]
Yes, I'm using some unstable features and you'll have to use unstable rust to compile the project.
For the LLVM error, I'm not quite sure what you did wrong but you can try going over the instructions of the llvm-sys crate again. If you just want to try out the compiler without actually running code, you could also pass the --no-default-features flag but you won't be able to run any eye program because I'm currently relying on LLVM as a codegen backend:
`cargo run --no-default-features -- check example.eye`

**Comment by LinusDikomey** [comment]
I'm closing this for now, I also added build instructions to the README.
